global:
  scrape_interval: 5s

scrape_configs:
  - job_name: 'match-service'
    static_configs:
      - targets: ['match-service:3000']
  - job_name: 'user-service'
    static_configs:
      - targets: ['user-service:3001']
  # - job_name: 'gamification-service'
  #   static_configs:
  #     - targets: ['localhost:3002']
  # - job_name: 'notification-service'
  #   static_configs:
  #     - targets: ['localhost:3003']
